instance_create_depth(x, y + 8, depth, obj_world_map_butt)
instance_create_depth(x+64, y + 4, depth, obj_tower_menu_butt)
instance_create_depth(x+128, y, depth, obj_bloon_menu_butt)
instance_create_depth(x+192, y - 4, depth, obj_settings_menu_butt)
instance_create_depth(x+256, y - 8, depth, obj_credits_menu_butt)